version: "3"

services:
  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

  api:
    build: .
    container_name: proiot_api
    restart: always
    command: npm run start
    volumes:
      - ./src:/usr/src/proiot/src
      - ./dist:/usr/src/proiot/dist
      - ./package.json:/usr/src/proiot/package.json
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - mongo_network

volumes:
  mongo_data:

networks:
  mongo_network:
    driver: bridge
